packages/ui/src/routes/ReminderPage.tsx

Backup page form fix
The first step of seed phrase backup requests the password. That form was not working correctly and this PR applies the needed fixes to the input and state. Reported by @NODRAJ .

[Fix] Backup page form

---

.github/workflows/build.yml
.github/workflows/ci.yml
README.md
packages/background/Makefile
packages/background/package.json
packages/background/src/controllers/TransactionWatcherController.ts
packages/background/src/controllers/erc-20/TokenList.ts
packages/background/src/infrastructure/stores/migrator/migrations/index.ts
packages/background/src/infrastructure/stores/migrator/migrations/migration-43.ts
packages/background/src/utils/constants/networks.ts
packages/provider/Makefile
packages/ui/src/components/setup/SeedImport.tsx
packages/ui/src/routes/networks/NetworkFormPage.tsx
packages/ui/src/routes/setup/PasswordSetupPage.tsx

Add new tesnet called [zkSync (v2)](https://v2-docs.zksync.io/dev/)
- Add the new testnet in the networks list
- Add migration
- Fix wrong "terms and conditions" url

Add zksync alpha tesnet

---

packages/provider/Makefile

Provider MAKEFILE fix
This PR applies a small fix on the provider's package makefile regarding production mode build.

Provider MAKEFILE fix

---

packages/background/src/controllers/BlankController.ts
packages/background/src/controllers/BridgeController.ts
packages/background/src/controllers/SwapController.ts
packages/background/src/controllers/TokenAllowanceController.ts
packages/background/src/controllers/erc-20/TokenController.ts
packages/background/src/controllers/erc-20/transactions/TokenAllowanceController.ts
packages/background/src/infrastructure/stores/ObservableStore.ts
packages/background/src/utils/token.ts
packages/background/test/controllers/AddressBookController.test.ts
packages/background/test/controllers/BridgeController.test.ts
packages/background/test/controllers/SwapController.test.ts

Refactor token allowance logic for swaps and bridges
Token allowance code was encapsulated using a non-conventional inheritance. This PR creates a separate controller to encapsulate this logic.
Refactor

[Refactor] Token Allowance controller

---

.github/CODEOWNERS
README.md
docs/convention.md

Remove convention CI from the docs
Remove old references in the docs

docs: remove pipeline references in convention

---

packages/ui/src/components/chain/ChainDisplay.tsx
packages/ui/src/routes/networks/SearchNetworkPage.tsx

Network search results spacing
Adjust networks search results spacing to be consistent with add token search spacing.

style: adjust add networks search results spacing

---

packages/background/src/infrastructure/stores/migrator/migrations/migration-43.ts
packages/background/src/utils/constants/networks.ts

Updated zkSync explorer
updated zkSync block explorer url

chore: updated zkSync block explorer url.

---

packages/ui/src/assets/images/icons/accounts.svg
packages/ui/src/components/account/AccountMenu.tsx
packages/ui/src/routes/PopupPage.tsx

My accounts tooltip text consistency

fix: my accounts tooltip text consistency

---

.github/workflows/build.yml
.github/workflows/release.yml

Add @julianariel to the slack messages related to the release process
Add @julianariel to the slack messages related to the release process

chore: add Julian to slack messages

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.4.1.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.4.1.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.4.1.checksum)

[Automated] Extension release v0.4.1

---

packages/background/src/controllers/ExchangeRatesController.ts
packages/background/src/utils/rateService.ts

Chainlink network provider param
Fix network provider param as it was being received as undefined so Chainlink contract was failing. Fixed the implementation of GetRate method.

[Fix] Chainlink network provider param

---

packages/background/src/controllers/BridgeController.ts
packages/background/src/utils/bridgeApi.ts

Improve error handling in the quote request
To avoid an unexpected error

fix: improve error handling

---

packages/background/src/controllers/BridgeController.ts
packages/background/src/utils/bridgeApi.ts
packages/background/src/utils/incomingBridgePlaceholder.ts

fix: build warnings

---

packages/background/src/controllers/ExchangeController.ts
packages/background/src/utils/types/1inch.ts
packages/ui/src/routes/swap/SwapPage.tsx

Enable swaps fees
This PR enables a 0.5% of fees for every swap done using the wallet.

[Feat] Enable swaps fees

---

packages/ui/src/components/transactions/TransactionDetailsBasic.tsx
packages/ui/src/components/transactions/TransactionItem.tsx

Big amount and token name in the transactions section glitch the UI.

fix: big amount & token name glitch

---

packages/ui/src/components/transactions/TransactionItem.tsx

transaction message truncate to prevent overflow of container

fix: transaction message truncate width

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.4.2.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.4.2.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.4.2.checksum)

[Automated] Extension release v0.4.2

---

packages/ui/src/routes/bridge/BridgeSetupPage.tsx

Focus amount input when clicking on the div

[Feat] Focus on amount input when clicking the blue square

---

packages/ui/src/routes/bridge/BridgeConfirmPage.tsx

Fix messages related to bridge allowance token

[Fix] Change text related to bridge allowance token

---

packages/ui/src/routes/dApp/AddEthereumChain.tsx

dapp add network unknown chainID misplaced tooltip

[Fix] Add network page misplaced tooltip

---

packages/ui/src/routes/UnlockPage.tsx

lock timeout tooltip position
This PR fixes lock timeout tooltip positon at unlock page.

[Style] lock timeout tooltip position

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.5.0.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.5.0.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.5.0.checksum)

[Automated] Extension release v0.5.0

---

packages/background/src/controllers/BlankProviderController.ts
packages/background/src/utils/signature.ts
packages/background/src/utils/types/ethereum.ts
packages/ui/src/components/ui/CodeBlock.tsx
packages/ui/src/routes/dApp/SignPage.tsx

Display the message to be signed before converting it to hex.
This PR closes the #234

[Fix] Show original text in the SignPage

---

packages/ui/src/routes/send/SendPage.tsx

Remove add to contacts if the address is in my accounts.

[Fix] Add to contacts if in my accounts

---

packages/background/src/controllers/BridgeController.ts

Improve bridge networks fetching process
This PR aims to improve the process of fetching available networks for bridges by: 
- Re-fetching chains every time the user changes the network
- Add retires in case of error
- Improve error logging by adding the error returned by the API

[feat] Improve bridge chains fetching process

---

packages/ui/src/components/error/ErrorFallbackPage.tsx
packages/ui/src/util/constants.ts

Button on the error page to report a bug.
Addition of a button to the bug report in GitHub and some UX improvements.

[Feat] Button on error page to report bug

---

packages/background/package.json
packages/background/src/infrastructure/stores/migrator/migrations/migration-53.ts
packages/background/src/utils/constants/networks.ts
packages/background/yarn.lock

- Update RSK and ZKsync testnet endpoints
- Use BlockWallet nodes in RSK and ZKsync testnet networks

[Feat] Update RSK and ZKsync testnet endpoints

---

packages/background/src/controllers/erc-20/TokenController.ts
packages/ui/src/components/input/NetworkSelect.tsx
packages/ui/src/components/loading/TransparentOverlay.tsx
packages/ui/src/components/token/AddTokenManualView.tsx
packages/ui/src/routes/PopupPage.tsx
packages/ui/src/routes/settings/AddTokensPage.tsx
packages/ui/src/util/__tests__/account.test.ts
packages/ui/src/util/account.ts

Add token logo & duplicated symbol
If token doesnt have logo, we dont add it from any other token in chain. We allow more than one token with same symbol in same network.

[Fix] Add token logo

---

packages/background/src/index.ts

Uninstall form
Added uninstall URL property to open a form to gather feedback when users uninstall the wallet.

[Feat] Uninstall Form

---

packages/provider/src/utils/compatibility.ts

Clean code 
Remove code used only for development purposes.

[Fix] Remove dev code

---

packages/ui/src/components/info/ReleaseNotesInfo.tsx
packages/ui/src/util/constants.ts

Link to changelog on Release Notes
Added a constant and href pointing to changelog article on release notes oage.

[Chore] Link to changelog on Release Notes

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.5.1.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.5.1.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.5.1.checksum)

[Automated] Extension release v0.5.1

---

packages/background/package.json
packages/background/yarn.lock
packages/provider/package.json
packages/provider/yarn.lock

[Chore] Bump remote config version to 1.1.0

---

packages/background/src/controllers/ExchangeRatesController.ts
packages/ui/src/routes/PopupPage.tsx

Error handling on exchangeRates
Error handling on exchangeRates caused a bug on networks like ETHW where the exchange rates is not always available

[Fix] Error handling on exchangeRates

---

public/manifest.json

Update description on manifest file
Updated BlockWallet's description on the manifest file to display it on the browser's extension store.

[Chore] Update description on manifest file

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.5.2.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.5.2.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.5.2.checksum)

[Automated] Extension release v0.5.2

---

packages/background/package.json
packages/background/src/utils/rateService.ts
packages/background/yarn.lock

This PR aims to fix the rates fetching for the Ethereum POW fork.

fixing rates for ETH POW

---

package.json
public/manifest.json
release-notes.json

Reverts block-wallet/extension#282 in order to create a new one with the latest fixes.

Revert "[Automated] Extension release v0.5.2"

---

packages/background/package.json
packages/background/src/controllers/AccountTrackerController.ts
packages/background/src/controllers/BlankController.ts
packages/background/src/controllers/TransactionWatcherController.ts
packages/background/src/controllers/erc-20/Token.ts
packages/background/src/controllers/erc-20/TokenController.ts
packages/background/src/controllers/erc-20/transactions/DepositTransaction.ts
packages/background/src/controllers/erc-20/transactions/Transaction.ts
packages/background/src/controllers/transactions/TransactionController.ts
packages/background/src/infrastructure/stores/migrator/migrations/index.ts
packages/background/src/infrastructure/stores/migrator/migrations/migration-55.ts
packages/background/src/utils/types/communication.ts
packages/background/test/controllers/erc-20/TokenController.test.ts
packages/background/test/controllers/erc-20/transactions/Transaction.test.ts
packages/ui/src/components/assets/AssetSelection.tsx
packages/ui/src/components/token/AddTokenManualView.tsx
packages/ui/src/context/commActions.ts
packages/ui/src/routes/dApp/ApproveAsset.tsx
packages/ui/src/routes/dApp/ApproveNFT.tsx
packages/ui/src/routes/settings/AddTokensPage.tsx
packages/ui/src/routes/withdraw/WithdrawBlankConfirm.tsx

Fix token stored with decimals = -1
Due to a bug in the token fetch, some tokens were stored with their decimals = -1. This PR fixes that bug and implements a migration to fix broken states.

[Fix] Invalid tokens decimals

---

packages/background/package.json
packages/background/src/infrastructure/stores/migrator/migrations/index.ts
packages/background/src/infrastructure/stores/migrator/migrations/migration-56.ts
packages/background/src/utils/constants/networks.ts

RSK rebranded to Rootstock
This PR updates network names from RSK to Rootstock.

[Chore] RSK rebrand to Rootstock

---

packages/ui/src/components/token/AddTokenManualView.tsx

Duplicated symbol message validation
Fix validation to show duplicated symbol message when address is different

[Fix] Duplicated symbol message validation

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.5.3.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.5.3.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.5.3.checksum)

[Automated] Extension release v0.5.3

---

packages/background/src/controllers/BlankProviderController.ts

fixing gas limit estimation for all the dapps

fixing gas limit estimation for all the dapps

---

.github/workflows/build.yml
.github/workflows/ci.yml
README.md
packages/background/src/controllers/PermissionsController.ts

Deprecate private libs
- Remove NPM token
- Update readme

[Chore] Deprecate private libs

---

packages/ui/src/components/qr/qr-reader.tsx
packages/ui/src/router/TabRouter.tsx
packages/ui/src/routes/hardware-wallet/KeystoneConnectionPage.tsx
packages/ui/src/routes/hardware-wallet/SetupLayout.tsx
packages/ui/src/routes/hardware-wallet/VendorsPage.tsx
packages/ui/src/util/connectionStepUtils.tsx

Feat/keystone UI

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.5.5.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.5.5.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.5.5.checksum)

[Automated] Extension release v0.5.5

---

packages/background/src/utils/types/1inch.ts

1inch Custom API endpoint
1inch provided us with a custom API endpoint that would help us get analytics from its usage and filter out transactions in the future.

[Core] 1inch Custom API endpoint

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.5.6.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.5.6.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.5.6.checksum)

[Automated] Extension release v0.5.6

---

packages/background/package.json
packages/background/yarn.lock

Add Verse token to the Ethereum network
Add Verse token to the Ethereum network by adding it to the assets repo and updating the release version in the background.

[Feat] Add Verse token to eth

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.5.7.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.5.7.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.5.7.checksum)

[Automated] Extension release v0.5.7

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.6.0.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.6.0.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.6.0.checksum)

[Automated] Extension release v0.6.0

---

packages/ui/src/components/FullCenterContainer.tsx
packages/ui/src/components/PageLayout.tsx
packages/ui/src/components/dialog/DisabledFeatureDialog.tsx
packages/ui/src/components/dialog/FullScreenDialog.tsx
packages/ui/src/components/dialog/IsBetaDialog.tsx
packages/ui/src/components/info/WelcomeInfo.tsx
packages/ui/src/routes/IntroductionPage.tsx
packages/ui/src/routes/PopupPage.tsx
packages/ui/src/routes/account/CreateAccountPage.tsx
packages/ui/src/routes/hardware-wallet/RemoveSuccessPage.tsx
packages/ui/src/routes/settings/SettingsPage.tsx
packages/ui/src/routes/setup/BackupNoticePage.tsx
packages/ui/src/routes/setup/PasswordSetupPage.tsx
packages/ui/src/routes/setup/SeedImportPage.tsx
packages/ui/src/routes/setup/SetupPage.tsx

UI Changes
Adding warnings to indicate this is a beta version. It is done on the onboarding and for swap/bridge/HW feature

[Beta] UI Changes

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.7.0.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.7.0.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.7.0.checksum)

[Automated] Extension release v0.7.0

---

packages/ui/src/components/allowances/AllowanceItem.tsx
packages/ui/src/components/transactions/AllowanceInput.tsx
packages/ui/src/routes/dApp/ApproveAsset.tsx
packages/ui/src/routes/dApp/ApproveNFT.tsx
packages/ui/src/routes/transaction/ApprovePage.tsx
packages/ui/src/util/formatRounded.ts

Allowance page stuck + decimals UI fix
This PR fixes error when the rejecting allowance (current behaviour is stuck on page until restart) and decimals visibility in UI.

[Fix] Allowance page stuck + decimals UI fix

---

.github/workflows/ci.yml

remove CI with dependabot PRs
dependabot won't trigger any pipeline

chore: remove CI with dependabot PRs

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.7.2.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.7.2.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.7.2.checksum)

[Automated] Extension release v0.7.2

---

packages/background/package.json
packages/background/src/infrastructure/stores/migrator/migrations/index.ts
packages/background/src/infrastructure/stores/migrator/migrations/migration-65.ts
packages/background/src/utils/constants/networks.ts

Mainnet intervals
We have received many reports about Mainnet taking more time than it should to update transaction statuses and balances, so this PR aims to implement the fast intervals set up and then see if it improves.

[Chore] Mainnet intervals

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.7.3.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.7.3.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.7.3.checksum)

[Automated] Extension release v0.7.3

---

packages/background/src/controllers/erc-20/TokenController.ts
packages/background/src/controllers/transactions/TransactionController.ts
packages/background/src/controllers/transactions/utils/types.ts
packages/background/src/utils/http.ts
packages/ui/src/routes/dApp/ApproveNFT.tsx

Fixes #438 
Extension should not fail if the token total supply cannot be fetched for ERC721 tokens.

[Fix]: do not fail is total supply cannot be fetched

---

packages/ui/package.json
packages/ui/src/routes/dApp/SignPage.tsx
packages/ui/src/routes/settings/ExportDonePage.tsx
packages/ui/src/styles/index.css
packages/ui/yarn.lock

Replace react-json-view
Replace react-json-view because it's unmaintained and contains vulnerabilities

[Fix] Replace react-json-view

---

packages/background/package.json
packages/background/src/controllers/erc-20/TokenList.ts
packages/background/yarn.lock

chains-assets update
Updated chains-assets version with the latest release and imported blockchain's map from the lib.

[Core] chains-assets update

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.7.4.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.7.4.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.7.4.checksum)

[Automated] Extension release v0.7.4

---

packages/background/src/controllers/AccountTrackerController.ts
packages/background/src/controllers/BlankController.ts
packages/background/src/controllers/NotificationController.ts

Add address name to notifications
Add address name to notifications from wallet account, address book contacts or from ens lookup.

[Feat] Add address name to notifications

---

packages/background/src/controllers/BlankController.ts
packages/background/src/controllers/OnrampController.ts

improving store management

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v0.7.5.zip)
- [Release notes screenshot](https://releases.blockwallet.io/extension/block-wallet-v0.7.5.png)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v0.7.5.checksum)

[Automated] Extension release v0.7.5

---

.github/workflows/build.yml

Removed E2E from the release process

[Core] Removed E2E from release process

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v1.0.0.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v1.0.0.checksum)

[Automated] Extension release v1.0.0

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v1.0.1.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v1.0.1.checksum)

[Automated] Extension release v1.0.1

---

packages/ui/src/routes/dApp/ApproveAsset.tsx
packages/ui/src/util/approval.ts

[fix] fallback to unlimited allowance in case it is larger than expected

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v1.1.1.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v1.1.1.checksum)

[Automated] Extension release v1.1.1

---

packages/background/package.json
packages/background/src/infrastructure/stores/migrator/migrations/migration-67.ts

`currentRpcUrl` property
Fixed migration to verify `currentRpcUrl` property because we received broken instances with that property missing on the state.

[Fix] currentRpcUrl property

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v1.1.2.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v1.1.2.checksum)

[Automated] Extension release v1.1.2

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v1.1.3.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v1.1.3.checksum)

[Automated] Extension release v1.1.3

---

packages/background/package.json
packages/background/src/controllers/PreferencesController.ts
packages/background/src/infrastructure/stores/migrator/migrations/index.ts
packages/background/src/infrastructure/stores/migrator/migrations/migration-68.ts
packages/background/src/utils/constants/initialState.ts
packages/background/test/infrastructure/stores/migrator/reconciler.test.ts
packages/background/test/mocks/mock-preferences.ts
packages/background/test/utils/userPreferences.test.ts
packages/ui/package.json
packages/ui/src/components/account/AccountDisplay.tsx
packages/ui/src/context/hooks/useNetWorthBalance.ts
packages/ui/src/mock/MockBackgroundState.tsx
packages/ui/src/routes/PopupPage.tsx
packages/ui/yarn.lock

Switch Net Worth <> Native Token
Added a switch button to opt between net worth and native token balance.
https://github.com/block-wallet/extension/assets/11839151/c973e246-27ac-4299-83e6-b73588b75e83

[Feat] Switch Net Worth <> Native Token

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v1.1.4.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v1.1.4.checksum)

[Automated] Extension release v1.1.4

---

packages/ui/src/routes/PopupPage.tsx

Tooltip on QR icon
added a tooltip to QR icon on homepage.

feat: Tooltip on QR icon

---

packages/ui/yarn.lock

Dependencies updates
Ran `yarn-audit-fix` on the UI package to update non-breaking dependencies.

[Core] Dependencies updates

---

packages/background/contributing.md
packages/ui/src/components/phishing/AntiPhishing.tsx
packages/ui/src/components/transactions/TransactionItem.tsx
packages/ui/src/routes/account/AllowancesPage.tsx
packages/ui/src/routes/hardware-wallet/AccountsPage.tsx
packages/ui/src/routes/hardware-wallet/VendorsPage.tsx
packages/ui/src/routes/settings/Hotkeys.tsx
packages/ui/src/util/constants.ts

Replace Zendesk links
Replaced old zendesk links with new ones from the website.

[Core] Replace Zendesk links

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v1.1.6.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v1.1.6.checksum)

[Automated] Extension release v1.1.6

---

docs/convention.md
docs/guideline.md
docs/workflow.md

fix: typos

---

packages/background/package.json
packages/background/yarn.lock

[Core] Updated assets

---

packages/background/package.json
packages/background/src/controllers/NetworkController.ts
packages/background/yarn.lock
packages/ui/src/routes/networks/NetworkFormPage.tsx

Updated assets and fixed bugs
Fixed network native currency icon evaluation and bug after adding a new network.

feat: updated assets and fixed bugs in network addition.

---

package.json
public/manifest.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v1.1.7.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v1.1.7.checksum)

[Automated] Extension release v1.1.7

---

manifest/base.json
package.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v1.2.0.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v1.2.0.checksum)
- [Firefox Extension zip](https://releases.blockwallet.io/extension/block-wallet-firefox-v1.2.0.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-firefox-v1.2.0.checksum)

[Automated] Extension release v1.2.0

---

packages/background/package.json
packages/background/src/controllers/NetworkController.ts
packages/background/src/infrastructure/stores/migrator/migrations/index.ts
packages/background/src/infrastructure/stores/migrator/migrations/migration-71.ts
packages/background/src/infrastructure/stores/migrator/migrations/migration-72.ts
packages/background/src/utils/constants/networks.ts

Scroll Mainnet addition
This PR adds the new Scroll mainnet to our list of default networks and also updates the current testnet to the new Sepolia Testnet.

[Feat] Scroll mainnet

---

packages/background/src/utils/bridgeApi.ts
packages/background/src/utils/types/lifi.ts
packages/background/test/controllers/BridgeController.test.ts
packages/ui/src/components/transactions/BridgeNotFoundQuoteDetails.tsx

LiFi Error Responses
This PR adjusts error types to adapt to the new structure that comes from LiFi responses.

[Fix] LiFi Error Responses

---

manifest/base.json
package.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v1.2.1.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v1.2.1.checksum)
- [Firefox Extension zip](https://releases.blockwallet.io/extension/block-wallet-firefox-v1.2.1.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-firefox-v1.2.1.checksum)

[Automated] Extension release v1.2.1

---

manifest/base.json
package.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v1.2.2.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v1.2.2.checksum)
- [Firefox Extension zip](https://releases.blockwallet.io/extension/block-wallet-firefox-v1.2.2.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-firefox-v1.2.2.checksum)

[Automated] Extension release v1.2.2

---

packages/background/package.json
packages/background/yarn.lock

Updated assets
Updated assets repo and version.

Updated assets.

---

packages/ui/src/components/home/AssetsList.tsx
packages/ui/src/components/transactions/TransactionItem.tsx
packages/ui/src/components/transactions/TransactionsList.tsx

[Fix] Assets & Transaction List
After adding List react component, hover changed from original desing. We did the changes to keep it as the original was.

[Fix] Assets & Transaction List

---

manifest/base.json
package.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v1.2.3.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v1.2.3.checksum)
- [Firefox Extension zip](https://releases.blockwallet.io/extension/block-wallet-firefox-v1.2.3.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-firefox-v1.2.3.checksum)

[Automated] Extension release v1.2.3

---

packages/ui/src/components/qr/TransactionShowQR.tsx

Keystone QR Generator
Fix keystone qr generation, as the param might by undefined the first time it has to be included in the useEffect that will generate the QR

[WIP][Fix] Keystone QR Generator

---

manifest/base.json
package.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v1.2.4.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v1.2.4.checksum)
- [Firefox Extension zip](https://releases.blockwallet.io/extension/block-wallet-firefox-v1.2.4.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-firefox-v1.2.4.checksum)

[Automated] Extension release v1.2.4

---

manifest/base.json
package.json
release-notes.json

- [Extension zip](https://releases.blockwallet.io/extension/block-wallet-v1.2.5.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-v1.2.5.checksum)
- [Firefox Extension zip](https://releases.blockwallet.io/extension/block-wallet-firefox-v1.2.5.zip)
- [SHA256 checksum](https://releases.blockwallet.io/extension/block-wallet-firefox-v1.2.5.checksum)

[Automated] Extension release v1.2.5
