block-wallet/extension

- packages/background/src/controllers/ActivityListController.ts
- packages/background/src/controllers/transactions/utils/types.ts
- packages/background/src/utils/incomingBridgePlaceholder.ts
- packages/ui/src/components/transactions/TransactionItem.tsx
- packages/ui/src/context/commTypes.ts
- packages/ui/src/util/transactionUtils.ts
Bridging
This pr meant to show the incoming bridging transactions before we already know the destination transaction hash so that the user can see the "Incoming bridge" transaction in their activity list while it is pending.
https://user-images.githubusercontent.com/22504074/192754076-6d2fe986-b1e5-43e9-9927-e7c5bf6a1e4b.mov
> feat: Show incoming bridge placeholder in destination network

- packages/ui/src/components/transactions/TransactionItem.tsx
- packages/ui/src/util/account.ts
- packages/ui/src/util/isNil.ts
Fix a bug in the Transaction details when trying to show the nonce of a non-mined tx.
The isNil check was not implemented properly. Also, some corner cases were handled in this PR, like when we cannot get a transaction label (due to using an old build with newer transaction categories)
> [Fix] isNil logic 

- .github/pull_request_template.md
Remove "type of change"
We want to replace "type of change" with the PR labels
> docs: remove type of change

- .github/workflows/ci.yml
- .github/workflows/skip_e2e.yml
CI pipeline restrictions
- Run the CI pipeline (lint, test, build and e2e) only when:
- There's an open PR with master as a target branch
- Some files were modified (.js, .ts, etc)
- Add "fake" e2e : If a workflow is skipped due to [path filtering](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpushpull_requestpull_request_targetpathspaths-ignore), [branch filtering](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions#onpull_requestpull_request_targetbranchesbranches-ignore) or a [commit message](https://docs.github.com/en/actions/managing-workflow-runs/skipping-workflow-runs), then checks associated with that workflow will remain in a "Pending" state. A pull request that requires those checks to be successful will …
> CI pipeline restrictions

- packages/ui/src/components/input/NetworkSelect.tsx
- packages/ui/src/routes/networks/NetworkFormPage.tsx
- packages/ui/src/routes/networks/NetworksPage.tsx
Extension breaks when new network is added and pressed in the goBack arrow.
The network flow broke after removing the imperative go back function to the settings page from the networks page. its a really complicated flow to be handled that way as it can be reached from different parts of the application like:
- After adding/editing/removing a network
- Going back from the Search networks page
- From the home page
- From the settings page.
> [Fix] Use imperative go back routes to avoid crash networks flow

- public/manifest.json
This PR aims to fix an issue in the current manifest related to the wasm files.
Once we upgrade our manifest to V3 this won't be an issue anymore because we won't need any wasm files.
> Allowing wasm execution on the last chrome version

- packages/ui/src/components/assets/AssetDetailsPage.tsx
- packages/ui/src/components/assets/AssetSelection.tsx
- packages/ui/src/components/token/AddTokenManualView.tsx
- packages/ui/src/components/token/TokenDisplay.tsx
- packages/ui/src/components/token/TokenLogo.tsx
Add balance and asset Name on DisplayToken
Showing Token Name + Token Symbol as Standard. We sanitize Token Name in case it is too long. Also retrieve TokenLogo changes from Bridging branch, as it affects TokenDisplay.
> [Feat] Add balance and asset Name on DisplayToken

- packages/background/package.json
- packages/background/src/controllers/TransactionWatcherController.ts
- packages/background/src/infrastructure/stores/migrator/migrations/index.ts
- packages/background/src/infrastructure/stores/migrator/migrations/migration-46.ts
- packages/ui/src/components/transactions/TransactionDetailsBasic.tsx
- packages/ui/src/util/hooks/useCopyToClipboard.ts
- packages/ui/src/util/transactionUtils.ts
Fix some issues related to the transaction details for the token transfer transactions
When opening a transaction details of a token transfer transaction:
- The `transactionTo` is not 100% accurate since we are putting the contract address and not the destination address of the transfer.
- The incoming transactions are parsing the tx fees as the value of the transaction, making the dialog to behave in a weird way.
> [Fix] Transaction details for token transfers

- packages/background/src/infrastructure/stores/migrator/migrations/migration-48.ts
Normalize networks order
added normalize networks order method to new migration to prevent gaps and incorrect orders.
> fix: added normalize networks order to new migration.

- Makefile
UI Sourcemaps in Production mode
This PR adds the `GENERATE_SOURCEMAP=false` flag in UI's production build script. These sourcemaps are not needed in prod and removing them makes the extension zipped 4MB smaller.
> [Chore] UI sourcemaps

- release-notes.json
Release Notes typo
Fixed release-notes typo. It was corrected manually before the release, this is just to replicate the fix in the repo.
> [Fix] Release notes typo

- packages/ui/src/components/setup/SeedImport.tsx
SeedImport OnPaste vs OnChange
OnPaste runs logic for seedPhrase with several words. If you paste only one word or you write one word it will run OnChange. If onPaste runs for one word it duplicates the line
> [Fix] SeedImport OnPaste vs OnChange

- packages/ui/src/components/popup/PopupHeader.tsx
- packages/ui/src/routes/bridge/BridgeConfirmPage.tsx
- packages/ui/src/routes/bridge/BridgeSetupPage.tsx
- packages/ui/src/routes/transaction/ApprovePage.tsx
Rollback the network indicator
When we merged the Bridging PR to master, the network indicator implementation in the PopupHeader was removed by mistake. This PR rollbacks that code and uses everywhere it was being rendered manually in the header.
> [Fix] Restore network indicator in the PopupHeader

- packages/ui/src/components/input/NetworkSelect.tsx
- packages/ui/src/components/loading/TransparentOverlay.tsx
- packages/ui/src/routes/PopupPage.tsx
Non-clickable network change when the provider is down
The network select was non-clickable from the provider down dialog due to the loading transparent overlay.
> [Fix] Non-clickable network change when provider down

- packages/ui/src/components/setup/SeedImport.tsx
- packages/ui/src/routes/setup/PasswordSetupPage.tsx
Enable submit button on Seed Import/New account
Add logic to enable submit button when importing or creating new account. It checks all the fields are completed, after that it enables the button.
> [Fix] Enable submit button on Seed Import/New account

- packages/background/src/controllers/NetworkController.ts
- packages/background/src/utils/ethereumChain.ts
- packages/background/src/utils/nodes.ts
Use custom headers when using BlockWallet nodes
- **Every request** to a BlockWallet node should have this custom header. More info at https://github.com/block-wallet/proxy-failover/pull/8
> [Feat] use custom headers with BlockWallet nodes

- packages/ui/src/routes/swap/SwapConfirmPage.tsx
Flashbots on Swaps
This PR fixes #258 which prevented Flashbots from being enabled in swap transactions. The fix consists on adding gas limit parameter to the advanced settings modal.
> [Fix] Flashbots on Swaps

- packages/ui/src/components/account/AccountDisplay.tsx
- packages/ui/src/components/account/AccountMenu.tsx
- packages/ui/src/components/account/AccountSearchResults.tsx
- packages/ui/src/routes/PopupPage.tsx
- packages/ui/src/routes/send/SendPage.tsx
- packages/ui/src/util/hooks/useSelectedAddressWithChainIdChecksum.ts
Send to checksummed address with chain id
- Allow sending to a checksummed (with chain) address
- The copied value of the account should be checksummed with the chain id in RSK mainnet/testnet
- The copied value of the accounts in the transactions should be checksummed with the chain id in RSK mainnet/testnet
> [Fix] Send to checksummed address with chain id

- packages/ui/src/components/assets/AssetDetailsPage.tsx
- packages/ui/src/components/token/TokenSummary.tsx
margin top in Tokensumarry
Remove margin-top from tokenSummary, it was only needed in AssetDetails, not in popuppage
> [Fix] margin top in Tokensumarry

- packages/background/src/controllers/NetworkController.ts
- packages/background/src/utils/ethereumChain.ts
Restore custom header when using BlockWallet Nodes
- Add the custom header due to the CORS issue was fixed https://github.com/block-wallet/block-devops/pull/95
> [Fix] Restore custom header when using BlockWallet Nodes

- packages/ui/src/components/dialog/WaitingAllowanceTransactionDialog.tsx
- packages/ui/src/components/dialog/WaitingDialog.tsx
- packages/ui/src/context/hooks/useAwaitAllowanceTransactionDialog.tsx
- packages/ui/src/routes/bridge/BridgeConfirmPage.tsx
- packages/ui/src/routes/swap/SwapConfirmPage.tsx
- packages/ui/src/routes/transaction/ApprovePage.tsx
Improve allowance transactions status management for bridges and swaps
Currently, we are not managing pretty well the status an allowance transaction may transition in the middle of the swaps and bridges operations. Therefore, this PR listen to the status changes, shows proper messages and redirects user to the first step of the flow if the transaction has failed.
> [Fix]: Improve token allowance flow for bridges and swaps

- packages/background/src/controllers/BridgeController.ts
- packages/ui/src/components/transactions/GasPriceComponent.tsx
- packages/ui/src/components/transactions/GasPriceSelector.tsx
- packages/ui/src/routes/bridge/BridgeConfirmPage.tsx
- packages/ui/src/util/form.ts
Users were not able to introduce custom gas limit when executing a bridge.
As we come up with that Li.Fi sometimes does not estimate pretty well the gas limit, we decided to allow users to edit the transaction gas limit before executing it. However, we introduced a validation: The gas limit cannot be lower than the one suggested by Li.Fi
> [fix]: Allow users to edit gas limit on bridges

- packages/background/src/controllers/NetworkController.ts
Check provider status on extension reload
This PR adds a network provider check in the NetworkController constructor to recalculate its status. Currently a broken provider is fake ""fixed"" reloading the extension. Adding this check, we will have the real provider status even if the network was reloaded. This also submits the Network change status event no matter the provider fails, to sync every extension with the new network chain id.
> [Fix]: check provider status on extension reload

- packages/background/src/controllers/transactions/TransactionController.ts
- packages/ui/src/components/networks/NetworkDisplay.tsx
- packages/ui/src/routes/send/SendConfirmPage.tsx
The gas limit for tokens transfers is throwing wrong values.
In order to have more accurate gas limit estimations, we added the amount the user is transferring to the estimation request instead of hardcoding the amount to "1".
> [Fix]: Sends gas limit estimation

- packages/ui/src/components/CancelSpeedUpCommon.tsx
Not enough funds validation in cancel
Fix not enough funds validation in cancel as it didn't show before and transaction would fail with error modal
> [Fix] Not enough funds validation in cancel

- packages/background/src/controllers/transactions/TransactionController.ts
- packages/background/test/controllers/transactions/TransactionController.test.ts
EIP-1559 params on Legacy Transactions
This PR removed EIP-1559 parameters on legacy transactions after we detected that some dApps send both (i.e. [Velocore](https://app.velocore.xyz/swap)) on zkSync (non-EIP1559).
> [Fix] EIP-1559 params on Legacy Transactions

- packages/background/src/controllers/transactions/TransactionController.ts
It fixes #438 
The extension background is throwing an error when the tokenURI is either undefined/null or an empty string to prevent failing on approval requests
> [Fix] do not fail if token URI is empty string

- public/manifest.json
Storage Limit
After receiving some reports of strange behaviors on instances with many accounts, we detected that the state was full of data and exceeded the default limit. While we work on more improvements, the `unlimitedStorage` flag will prevent users from being stuck or rollbacks in wallet actions.
> [Core] Storage Limit

- packages/ui/src/routes/settings/AboutPage.tsx
About page links
Changed about page links to affect the whole button and not only the text by using the `onChange` method.
> [Fix] About page links

- packages/background/src/controllers/transactions/TransactionController.ts
Value parameter on Allowance transactions
We don't display a **Total** transaction value on the allowance approval page because it is only supposed to cost what the fees cost. This translates to the **value** parameter of the transaction having a **zero** or undefined value.
But we received transaction parameters from dApps and parse them without checking the **value**, which caused a potential loss of native assets if the user approved such a transaction.
This PR enforces an undefined value parameter for allowance transactions which should never require a value in the first place.
Credit goes to @jinukaloshaechi who reported it on Immunefi and Discord
> [Fix] Value parameter on Allowance transactions

- packages/ui/src/routes/hardware-wallet/KeystoneConnectionPage.tsx
Message on QR code camera screen
Added a message explaining that the blurred camera won't affect the scanning.
> [Fix] Message on QR code camera screen

- packages/background/test/controllers/NetworkController.test.ts
- packages/background/test/controllers/block-updates/BlockFetchController.test.ts
The current test suite fails with at least one test.
```sh
1) Network controller
EIP1559 compatibility
The chain fee service indicates NO EIP 1559 compatibility:
AssertionError: expected true to equal false
+ expected - actual
-true
+false
at Suite.<anonymous> (test/controllers/NetworkController.test.ts:136:50)
at Generator.next (<anonymous>)
at fulfilled (test/controllers/NetworkController.test.ts:28:58)
at processTicksAndRejections (node:internal/process/task_queues:96:5)
```
This is probably due to the check about the baseFee attribute for chainID [56](https://chain-fee.blockwallet.io/v1/fee_data?c=56):
```json
{"blockNumber":"31381181", "blockGasLimit":"140000000", "baseFee":"0", "estimatedBaseFee":"0", "gasPricesLevels":{"slow":{"maxFeePerGas":"1100000000", …
```
> Fixed NO EIP 1559 test

- packages/ui/src/routes/dApp/TransactionConfirmPage.tsx
- packages/ui/src/util/window.ts
Stuck at TX confirm
This PR removes the disabled state from reject button on dapp tx confirm page to prevent stuck apps.
> [Fix] Stuck at TX confirm

- packages/ui/src/components/token/TokenList.tsx
Bug Page receive filter
Receive filter was not working due to some html element keys were empty. We changed the key value to always have one.
> [Fix] Buy Page receive filter

- packages/background/src/controllers/GasPricesController.ts
- packages/background/src/controllers/NetworkController.ts
- packages/background/src/utils/swaps/1inch.ts
- packages/background/src/utils/swaps/openOcean.ts
- packages/ui/src/components/hardwareWallet/HardwareWalletAccount.tsx
- packages/ui/src/util/tokenUtils.ts
EIP-1559 Integrity check
Added new EIP1559 integrity check to force fetching the value again when we detect inconsistency between the value and the stored baseFee. We detected this situation on some old states from users which tried to perform an operation and received an error.
After checking the state, we noticed that some chains had the EIP-1559 flag with a `false` value when it should be true. The situation was automatically fixed after switching networks but it seems some users only operate with one network so this check should prevent this situation from happening again (i.e. a non EIP network upgrades to EIP-1559)
> [Fix] EIP-1559 Integrity check
